# Generated by Django 6.0 on 2025-12-17 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Orijinal şikayet metni', max_length=500)),
                ('normalized_text', models.TextField(blank=True, help_text='Düzenlenmiş metin', null=True)),
                ('category', models.CharField(choices=[('technical', 'Teknik'), ('service', 'Hizmet'), ('staff', 'Personel'), ('other', 'Diğer')], default='other', max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Düşük'), (2, 'Orta'), (3, 'Yüksek'), (4, 'Kritik')], default=1)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
