# Generated by Django 6.0 on 2025-12-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Original feedback text', max_length=500)),
                ('normalized_text', models.TextField(blank=True, help_text='Normalized text', null=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('service', 'Service'), ('staff', 'Staff'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('tone', models.CharField(choices=[('aggressive', 'Aggressive'), ('neutral', 'Neutral'), ('polite', 'Polite'), ('disappointed', 'Disappointed')], help_text='Detected user tone', max_length=20)),
                ('intent', models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('praise', 'Praise'), ('question', 'Question')], help_text='Detected user intent', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
