# Generated by Django 6.0 on 2025-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='intent',
            field=models.CharField(choices=[('complaint', 'Şikayet'), ('suggestion', 'Öneri'), ('praise', 'Övgü'), ('question', 'Soru')], default='complaint', help_text='Kullanıcının amacı', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tone',
            field=models.CharField(choices=[('aggressive', 'Agresif'), ('neutral', 'Nötr'), ('polite', 'Nazik'), ('disappointed', 'Hayal Kırıklığına Uğramış')], default='neutral', help_text='Kullanıcının algılanan tonu', max_length=20),
        ),
    ]
