# Generated by Django 6.0 on 2025-12-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_intent_alter_feedback_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('service', 'Service'), ('staff', 'Staff'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='intent',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('praise', 'Praise'), ('question', 'Question')], default='complaint', help_text='Detected user intent', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='normalized_text',
            field=models.TextField(blank=True, help_text='Normalized text', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='raw_text',
            field=models.TextField(help_text='Original feedback text', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tone',
            field=models.CharField(choices=[('aggressive', 'Aggressive'), ('neutral', 'Neutral'), ('polite', 'Polite'), ('disappointed', 'Disappointed')], default='neutral', help_text='Detected user tone', max_length=20),
        ),
    ]
