# Generated by Django 6.0 on 2025-12-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('education', 'Eğitim'), ('food', 'Beslenme/Yemek'), ('facility', 'Tesis/Altyapı'), ('it', 'Bilgi İşlem')], max_length=50)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
