# Generated by Django 6.0 on 2025-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('education', 'Eğitim'), ('food', 'Beslenme/Yemek'), ('facility', 'Tesis/Altyapı'), ('it', 'Bilgi İşlem')], max_length=50),
        ),
    ]
